### ISSUE TITLE
Connecting to discord

### ISSUE THREAD

**Issue by lyricalpaws** [Enerdy/DiscordBridge#2]
Every time I set it up fully, it goes the issue "Discord Bridge bot failed to connect. Check your internet connection and try again."

**Comment by AxisKriel** [comment]
This plugin no longer works with the current version of the Discord Web API. Please look for alternatives elsewhere, or wait for the eventual rewrite, though it may take awhile.

**Comment by AxisKriel** [comment]
Added a note on https://github.com/Enerdy/DiscordBridge/commit/675a8d6edf0cb5bc25361c3939f68710c387347e to make this clear.
